filebeat.inputs:
- type: filestream
  id: anhub-docker-logs
  enabled: true
  paths:
    - /usr/share/filebeat/app-logs/anhub.log
  parsers:
    - ndjson:
        target: ""
        add_error_key: true
  fields:
    log_source: anhub
  fields_under_root: true

- type: filestream
  id: payments-docker-logs
  enabled: true
  paths:
    - /usr/share/filebeat/app-logs/payments.log
  parsers:
    - ndjson:
        target: ""
        add_error_key: true
  fields:
    log_source: payments
  fields_under_root: true

- type: filestream
  id: workbench-docker-logs
  enabled: true
  paths:
    - /usr/share/filebeat/app-logs/workbench.log
  parsers:
    - ndjson:
        target: ""
        add_error_key: true
  fields:
    log_source: workbench
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]