input {
  # Listen for Beats agents (like Filebeat)
  beats {
    port => 5044
  }
}

filter {
  mutate {
    remove_field => [ "event", "agent", "ecs" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "anhub-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}